import mongoose from 'mongoose';
import dotenv from 'dotenv';
import Product from './models/Product';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/flipkart_clone';

const products = [
    {
        name: 'iPhone 15 Pro Max (256 GB) - Natural Titanium',
        category: 'electronics',
        subCategory: 'mobiles',
        description: 'iPhone 15 Pro Max features a strong and light titanium design with a textured matte-glass back.',
        images: [
            'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500',
            'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=500',
        ],
        price: 156900,
        originalPrice: 179900,
        discountPercentage: 13,
        rating: 4.6,
        reviewCount: 12543,
        inStock: true,
        stockQuantity: 50,
        variants: [
            { name: 'Storage', options: ['256 GB', '512 GB', '1 TB'] },
            { name: 'Color', options: ['Natural Titanium', 'Blue Titanium', 'White Titanium', 'Black Titanium'] },
        ],
        specifications: {
            'Display': '6.7 inch Super Retina XDR',
            'Processor': 'A17 Pro chip',
            'RAM': '8 GB',
            'Storage': '256 GB',
            'Camera': '48 MP + 12 MP + 12 MP',
            'Battery': '4422 mAh',
        },
        warranty: '1 Year Apple Warranty',
        seller: 'AppleRetailIndia',
        isSponsored: false,
    },
    {
        name: 'Samsung Galaxy S24 Ultra 5G (Titanium Black, 256 GB)',
        category: 'electronics',
        subCategory: 'mobiles',
        description: 'The Samsung Galaxy S24 Ultra features AI-powered features and S Pen.',
        images: [
            'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500',
        ],
        price: 129999,
        originalPrice: 144999,
        discountPercentage: 10,
        rating: 4.5,
        reviewCount: 8765,
        inStock: true,
        stockQuantity: 120,
        variants: [
            { name: 'Storage', options: ['256 GB', '512 GB', '1 TB'] },
            { name: 'Color', options: ['Titanium Black', 'Titanium Gray', 'Titanium Violet'] },
        ],
        specifications: {
            'Display': '6.8 inch Dynamic AMOLED 2X',
            'Processor': 'Snapdragon 8 Gen 3',
            'RAM': '12 GB',
            'Storage': '256 GB',
            'Camera': '200 MP + 50 MP + 12 MP + 10 MP',
            'Battery': '5000 mAh',
        },
        warranty: '1 Year Samsung Warranty',
        seller: 'SamsungOfficialStore',
        isSponsored: true,
    },
    {
        name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
        category: 'electronics',
        subCategory: 'audio',
        description: 'Industry-leading noise cancellation with Auto NC Optimizer.',
        images: [
            'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500',
        ],
        price: 26990,
        originalPrice: 34990,
        discountPercentage: 23,
        rating: 4.7,
        reviewCount: 5432,
        inStock: true,
        stockQuantity: 200,
        variants: [
            { name: 'Color', options: ['Black', 'Silver', 'Midnight Blue'] },
        ],
        specifications: {
            'Driver Unit': '30mm',
            'Frequency Response': '4Hz-40,000Hz',
            'Battery Life': '30 hours',
            'Charging': 'USB-C',
            'Weight': '250g',
        },
        warranty: '1 Year Sony Warranty',
        seller: 'SonyIndia',
        isSponsored: false,
    },
    {
        name: 'MacBook Air M3 (15 inch, 8GB RAM, 256GB SSD)',
        category: 'electronics',
        subCategory: 'laptops',
        description: 'Supercharged by M3. The remarkably thin 15" MacBook Air.',
        images: [
            'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
        ],
        price: 134900,
        originalPrice: 149900,
        discountPercentage: 10,
        rating: 4.8,
        reviewCount: 3456,
        inStock: true,
        stockQuantity: 75,
        variants: [
            { name: 'RAM', options: ['8 GB', '16 GB', '24 GB'] },
            { name: 'Storage', options: ['256 GB', '512 GB', '1 TB'] },
            { name: 'Color', options: ['Midnight', 'Starlight', 'Space Gray', 'Silver'] },
        ],
        specifications: {
            'Display': '15.3 inch Liquid Retina',
            'Processor': 'Apple M3 chip',
            'RAM': '8 GB',
            'Storage': '256 GB SSD',
            'Battery': 'Up to 18 hours',
            'Weight': '1.51 kg',
        },
        warranty: '1 Year Apple Warranty',
        seller: 'AppleRetailIndia',
        isSponsored: false,
    },
    {
        name: 'Nike Air Jordan 1 Retro High OG - Chicago',
        category: 'fashion',
        subCategory: 'footwear',
        description: 'The Air Jordan 1 High remakes the classic sneaker with premium materials.',
        images: [
            'https://images.unsplash.com/photo-1600269452121-4f2416e55c28?w=500',
        ],
        price: 16995,
        originalPrice: 19995,
        discountPercentage: 15,
        rating: 4.4,
        reviewCount: 2345,
        inStock: true,
        stockQuantity: 45,
        variants: [
            { name: 'Size', options: ['7', '8', '9', '10', '11', '12'] },
        ],
        specifications: {
            'Upper Material': 'Premium Leather',
            'Sole': 'Rubber',
            'Closure': 'Lace-up',
            'Style': 'High Top',
        },
        warranty: '3 Months Seller Warranty',
        seller: 'NikeOfficialStore',
        isSponsored: true,
    },
    {
        name: 'Levi\'s Men\'s 501 Original Fit Jeans',
        category: 'fashion',
        subCategory: 'clothing',
        description: 'The original jean. Signature straight leg, button fly.',
        images: [
            'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
        ],
        price: 2499,
        originalPrice: 4999,
        discountPercentage: 50,
        rating: 4.3,
        reviewCount: 8765,
        inStock: true,
        stockQuantity: 300,
        variants: [
            { name: 'Size', options: ['28', '30', '32', '34', '36', '38'] },
            { name: 'Color', options: ['Dark Blue', 'Light Blue', 'Black'] },
        ],
        specifications: {
            'Material': '100% Cotton',
            'Fit': 'Original Fit',
            'Rise': 'Regular Rise',
            'Closure': 'Button Fly',
        },
        warranty: '30 Days Return',
        seller: 'LevisOfficial',
        isSponsored: false,
    },
    {
        name: 'Samsung 55" Crystal 4K UHD Smart TV',
        category: 'electronics',
        subCategory: 'tv',
        description: 'Experience stunning Crystal 4K resolution with Dynamic Crystal Color.',
        images: [
            'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500',
        ],
        price: 42990,
        originalPrice: 64900,
        discountPercentage: 34,
        rating: 4.4,
        reviewCount: 6543,
        inStock: true,
        stockQuantity: 80,
        variants: [
            { name: 'Size', options: ['43 inch', '50 inch', '55 inch', '65 inch'] },
        ],
        specifications: {
            'Display': '55 inch Crystal UHD',
            'Resolution': '3840 x 2160',
            'HDR': 'HDR10+',
            'Smart TV': 'Tizen OS',
            'Refresh Rate': '60Hz',
        },
        warranty: '1 Year Samsung Warranty',
        seller: 'SamsungOfficialStore',
        isSponsored: false,
    },
    {
        name: 'Dyson V15 Detect Cordless Vacuum Cleaner',
        category: 'appliances',
        subCategory: 'vacuum',
        description: 'Reveals hidden dust with a laser. Powerful Dyson suction.',
        images: [
            'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=500',
        ],
        price: 59900,
        originalPrice: 69900,
        discountPercentage: 14,
        rating: 4.6,
        reviewCount: 1234,
        inStock: true,
        stockQuantity: 30,
        variants: [],
        specifications: {
            'Suction Power': '230 AW',
            'Runtime': 'Up to 60 minutes',
            'Bin Capacity': '0.76L',
            'Weight': '3.1 kg',
            'Filtration': 'HEPA',
        },
        warranty: '2 Years Dyson Warranty',
        seller: 'DysonIndia',
        isSponsored: false,
    },
    {
        name: 'Apple Watch Series 9 GPS 45mm Midnight Aluminium',
        category: 'electronics',
        subCategory: 'wearables',
        description: 'The ultimate device for a healthy life with double tap gesture.',
        images: [
            'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=500',
        ],
        price: 44900,
        originalPrice: 49900,
        discountPercentage: 10,
        rating: 4.7,
        reviewCount: 4567,
        inStock: true,
        stockQuantity: 100,
        variants: [
            { name: 'Size', options: ['41mm', '45mm'] },
            { name: 'Color', options: ['Midnight', 'Starlight', 'Silver', 'Pink', 'Red'] },
        ],
        specifications: {
            'Display': 'Always-On Retina LTPO OLED',
            'Chip': 'S9 SiP',
            'Storage': '64 GB',
            'Water Resistance': '50m',
            'Battery': '18 hours',
        },
        warranty: '1 Year Apple Warranty',
        seller: 'AppleRetailIndia',
        isSponsored: false,
    },
    {
        name: 'boAt Airdopes 141 TWS Earbuds with 42H Playtime',
        category: 'electronics',
        subCategory: 'audio',
        description: 'Experience epic sound with 8mm drivers and ENx Technology.',
        images: [
            'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500',
        ],
        price: 1099,
        originalPrice: 4490,
        discountPercentage: 76,
        rating: 4.1,
        reviewCount: 234567,
        inStock: true,
        stockQuantity: 5000,
        variants: [
            { name: 'Color', options: ['Black', 'White', 'Blue', 'Green'] },
        ],
        specifications: {
            'Driver Size': '8mm',
            'Playback Time': '42 hours total',
            'Bluetooth': '5.1',
            'Water Resistance': 'IPX4',
            'Charging': 'Type-C',
        },
        warranty: '1 Year boAt Warranty',
        seller: 'boAtOfficial',
        isSponsored: true,
    },
    {
        name: 'IKEA MALM Bed Frame with Storage - White',
        category: 'home',
        subCategory: 'furniture',
        description: 'Clean lines and a timeless look. With 4 large drawers.',
        images: [
            'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500',
        ],
        price: 24990,
        originalPrice: 29990,
        discountPercentage: 17,
        rating: 4.3,
        reviewCount: 876,
        inStock: true,
        stockQuantity: 25,
        variants: [
            { name: 'Size', options: ['Queen', 'King'] },
            { name: 'Color', options: ['White', 'Black-Brown', 'Oak Veneer'] },
        ],
        specifications: {
            'Material': 'Particleboard, Fibreboard',
            'Dimensions': '209 x 156 x 100 cm',
            'Max Load': '150 kg',
            'Drawers': '4',
        },
        warranty: '10 Years IKEA Warranty',
        seller: 'IKEAIndia',
        isSponsored: false,
    },
    {
        name: 'Philips Air Fryer HD9252/90 - 4.1L',
        category: 'appliances',
        subCategory: 'kitchen',
        description: 'Fry with up to 90% less fat. Rapid Air Technology.',
        images: [
            'https://images.unsplash.com/photo-1626509653291-18d9a934b9db?w=500',
        ],
        price: 7499,
        originalPrice: 12995,
        discountPercentage: 42,
        rating: 4.4,
        reviewCount: 12345,
        inStock: true,
        stockQuantity: 150,
        variants: [],
        specifications: {
            'Capacity': '4.1L',
            'Power': '1400W',
            'Temperature': 'Up to 200°C',
            'Timer': '60 minutes',
            'Weight': '4.5 kg',
        },
        warranty: '2 Years Philips Warranty',
        seller: 'PhilipsIndia',
        isSponsored: false,
    },
    // Additional Products
    {
        name: 'OnePlus 12 5G (Flowy Emerald, 256 GB)',
        category: 'electronics',
        subCategory: 'mobiles',
        description: 'The OnePlus 12 features Snapdragon 8 Gen 3 and Hasselblad Camera.',
        images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=500'],
        price: 64999,
        originalPrice: 69999,
        discountPercentage: 7,
        rating: 4.5,
        reviewCount: 5678,
        inStock: true,
        stockQuantity: 200,
        variants: [{ name: 'Storage', options: ['256 GB', '512 GB'] }],
        specifications: { 'Display': '6.82 inch LTPO AMOLED', 'Processor': 'Snapdragon 8 Gen 3', 'RAM': '12 GB' },
        warranty: '1 Year OnePlus Warranty',
        seller: 'OnePlusStore',
        isSponsored: false,
    },
    {
        name: 'Google Pixel 8 Pro (Bay Blue, 128 GB)',
        category: 'electronics',
        subCategory: 'mobiles',
        description: 'Google Pixel 8 Pro with Tensor G3 chip and advanced AI features.',
        images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500'],
        price: 99999,
        originalPrice: 106999,
        discountPercentage: 7,
        rating: 4.6,
        reviewCount: 3456,
        inStock: true,
        stockQuantity: 80,
        variants: [{ name: 'Storage', options: ['128 GB', '256 GB', '512 GB'] }],
        specifications: { 'Display': '6.7 inch LTPO OLED', 'Processor': 'Google Tensor G3', 'RAM': '12 GB' },
        warranty: '1 Year Google Warranty',
        seller: 'GoogleStore',
        isSponsored: true,
    },
    {
        name: 'Dell XPS 15 Laptop (Intel i7, 16GB RAM, 512GB SSD)',
        category: 'electronics',
        subCategory: 'laptops',
        description: 'Dell XPS 15 with stunning 15.6 inch OLED display.',
        images: ['https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=500'],
        price: 149990,
        originalPrice: 179990,
        discountPercentage: 17,
        rating: 4.5,
        reviewCount: 2345,
        inStock: true,
        stockQuantity: 40,
        variants: [{ name: 'RAM', options: ['16 GB', '32 GB'] }],
        specifications: { 'Display': '15.6 inch OLED', 'Processor': 'Intel Core i7-13700H', 'RAM': '16 GB' },
        warranty: '1 Year Dell Warranty',
        seller: 'DellIndia',
        isSponsored: false,
    },
    {
        name: 'ASUS ROG Strix G16 Gaming Laptop',
        category: 'electronics',
        subCategory: 'laptops',
        description: 'ROG Strix G16 with RTX 4060 for ultimate gaming.',
        images: ['https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500'],
        price: 124990,
        originalPrice: 149990,
        discountPercentage: 17,
        rating: 4.4,
        reviewCount: 1876,
        inStock: true,
        stockQuantity: 30,
        variants: [],
        specifications: { 'Display': '16 inch 165Hz', 'Processor': 'Intel Core i7-13650HX', 'GPU': 'RTX 4060' },
        warranty: '1 Year ASUS Warranty',
        seller: 'ASUSIndia',
        isSponsored: true,
    },
    {
        name: 'Samsung Galaxy Tab S9 Ultra (256GB, Wi-Fi)',
        category: 'electronics',
        subCategory: 'tablets',
        description: 'Galaxy Tab S9 Ultra with massive 14.6 inch display.',
        images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500'],
        price: 108999,
        originalPrice: 124999,
        discountPercentage: 13,
        rating: 4.6,
        reviewCount: 1234,
        inStock: true,
        stockQuantity: 50,
        variants: [{ name: 'Storage', options: ['256 GB', '512 GB'] }],
        specifications: { 'Display': '14.6 inch Super AMOLED', 'Processor': 'Snapdragon 8 Gen 2', 'RAM': '12 GB' },
        warranty: '1 Year Samsung Warranty',
        seller: 'SamsungOfficialStore',
        isSponsored: false,
    },
    {
        name: 'Apple iPad Pro M2 12.9 inch (256GB, Wi-Fi)',
        category: 'electronics',
        subCategory: 'tablets',
        description: 'iPad Pro with M2 chip and Liquid Retina XDR display.',
        images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=500'],
        price: 112900,
        originalPrice: 124900,
        discountPercentage: 10,
        rating: 4.8,
        reviewCount: 2567,
        inStock: true,
        stockQuantity: 60,
        variants: [{ name: 'Storage', options: ['256 GB', '512 GB', '1 TB'] }],
        specifications: { 'Display': '12.9 inch Liquid Retina XDR', 'Processor': 'Apple M2', 'Camera': '12MP + 10MP' },
        warranty: '1 Year Apple Warranty',
        seller: 'AppleRetailIndia',
        isSponsored: false,
    },
    {
        name: 'JBL Flip 6 Portable Bluetooth Speaker',
        category: 'electronics',
        subCategory: 'audio',
        description: 'JBL Flip 6 with powerful sound and IP67 waterproof rating.',
        images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500'],
        price: 11999,
        originalPrice: 14999,
        discountPercentage: 20,
        rating: 4.5,
        reviewCount: 8765,
        inStock: true,
        stockQuantity: 300,
        variants: [{ name: 'Color', options: ['Black', 'Blue', 'Red', 'Green', 'Pink'] }],
        specifications: { 'Output': '30W', 'Battery Life': '12 hours', 'Waterproof': 'IP67' },
        warranty: '1 Year JBL Warranty',
        seller: 'JBLIndia',
        isSponsored: false,
    },
    {
        name: 'Canon EOS R50 Mirrorless Camera',
        category: 'electronics',
        subCategory: 'cameras',
        description: 'Canon EOS R50 with 24.2MP sensor and 4K video.',
        images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500'],
        price: 74990,
        originalPrice: 84990,
        discountPercentage: 12,
        rating: 4.4,
        reviewCount: 567,
        inStock: true,
        stockQuantity: 25,
        variants: [],
        specifications: { 'Sensor': '24.2MP APS-C', 'Video': '4K 30fps', 'ISO': '100-32000' },
        warranty: '2 Years Canon Warranty',
        seller: 'CanonIndia',
        isSponsored: false,
    },
    {
        name: 'GoPro HERO12 Black Action Camera',
        category: 'electronics',
        subCategory: 'cameras',
        description: 'GoPro HERO12 with 5.3K video and HyperSmooth 6.0.',
        images: ['https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=500'],
        price: 44990,
        originalPrice: 49990,
        discountPercentage: 10,
        rating: 4.6,
        reviewCount: 2345,
        inStock: true,
        stockQuantity: 100,
        variants: [],
        specifications: { 'Video': '5.3K 60fps', 'Waterproof': '10m', 'Stabilization': 'HyperSmooth 6.0' },
        warranty: '1 Year GoPro Warranty',
        seller: 'GoProIndia',
        isSponsored: false,
    },
    {
        name: 'Adidas Ultraboost 23 Running Shoes',
        category: 'fashion',
        subCategory: 'footwear',
        description: 'Ultraboost 23 with Light BOOST midsole for incredible energy return.',
        images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500'],
        price: 14999,
        originalPrice: 19999,
        discountPercentage: 25,
        rating: 4.6,
        reviewCount: 4567,
        inStock: true,
        stockQuantity: 150,
        variants: [{ name: 'Size', options: ['7', '8', '9', '10', '11'] }],
        specifications: { 'Upper': 'Primeknit+', 'Midsole': 'BOOST', 'Outsole': 'Continental Rubber' },
        warranty: '6 Months Seller Warranty',
        seller: 'AdidasIndia',
        isSponsored: true,
    },
    {
        name: 'Puma RS-X Toys Sneakers',
        category: 'fashion',
        subCategory: 'footwear',
        description: 'Retro-inspired RS-X with bold colors and chunky design.',
        images: ['https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500'],
        price: 7999,
        originalPrice: 10999,
        discountPercentage: 27,
        rating: 4.3,
        reviewCount: 3456,
        inStock: true,
        stockQuantity: 200,
        variants: [{ name: 'Size', options: ['7', '8', '9', '10', '11'] }],
        specifications: { 'Upper': 'Mesh and Leather', 'Midsole': 'RS Technology', 'Style': 'Casual' },
        warranty: '3 Months Seller Warranty',
        seller: 'PumaIndia',
        isSponsored: false,
    },
    {
        name: 'Tommy Hilfiger Slim Fit Polo T-Shirt',
        category: 'fashion',
        subCategory: 'clothing',
        description: 'Classic Tommy Hilfiger polo in premium cotton.',
        images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500'],
        price: 2499,
        originalPrice: 4999,
        discountPercentage: 50,
        rating: 4.4,
        reviewCount: 6789,
        inStock: true,
        stockQuantity: 500,
        variants: [{ name: 'Size', options: ['S', 'M', 'L', 'XL', 'XXL'] }, { name: 'Color', options: ['Navy', 'White', 'Red', 'Black'] }],
        specifications: { 'Material': '100% Cotton', 'Fit': 'Slim Fit', 'Collar': 'Polo' },
        warranty: '30 Days Return',
        seller: 'TommyHilfiger',
        isSponsored: false,
    },
    {
        name: 'Allen Solly Formal Blazer',
        category: 'fashion',
        subCategory: 'clothing',
        description: 'Premium formal blazer for professional occasions.',
        images: ['https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500'],
        price: 5999,
        originalPrice: 9999,
        discountPercentage: 40,
        rating: 4.2,
        reviewCount: 2345,
        inStock: true,
        stockQuantity: 100,
        variants: [{ name: 'Size', options: ['38', '40', '42', '44', '46'] }],
        specifications: { 'Material': 'Polyester Blend', 'Fit': 'Regular', 'Pattern': 'Solid' },
        warranty: '30 Days Return',
        seller: 'AllenSolly',
        isSponsored: false,
    },
    {
        name: 'Fossil Gen 6 Smartwatch',
        category: 'electronics',
        subCategory: 'wearables',
        description: 'Fossil Gen 6 with Snapdragon 4100+ and Wear OS.',
        images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=500'],
        price: 19995,
        originalPrice: 24995,
        discountPercentage: 20,
        rating: 4.2,
        reviewCount: 3456,
        inStock: true,
        stockQuantity: 75,
        variants: [{ name: 'Color', options: ['Black', 'Rose Gold', 'Silver'] }],
        specifications: { 'Display': '1.28 inch AMOLED', 'OS': 'Wear OS', 'Battery': '24+ hours' },
        warranty: '2 Years Fossil Warranty',
        seller: 'FossilIndia',
        isSponsored: false,
    },
    {
        name: 'Samsung Galaxy Watch 6 Classic',
        category: 'electronics',
        subCategory: 'wearables',
        description: 'Galaxy Watch 6 Classic with rotating bezel.',
        images: ['https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=500'],
        price: 35999,
        originalPrice: 40999,
        discountPercentage: 12,
        rating: 4.5,
        reviewCount: 2345,
        inStock: true,
        stockQuantity: 60,
        variants: [{ name: 'Size', options: ['43mm', '47mm'] }],
        specifications: { 'Display': '1.4 inch Super AMOLED', 'OS': 'One UI Watch 5', 'Battery': '40 hours' },
        warranty: '1 Year Samsung Warranty',
        seller: 'SamsungOfficialStore',
        isSponsored: false,
    },
    {
        name: 'LG 655L Side by Side Refrigerator',
        category: 'appliances',
        subCategory: 'refrigerator',
        description: 'LG 655L with InstaView Door-in-Door and Linear Cooling.',
        images: ['https://images.unsplash.com/photo-1571175443880-49e1d25b2bc5?w=500'],
        price: 89990,
        originalPrice: 119990,
        discountPercentage: 25,
        rating: 4.4,
        reviewCount: 1234,
        inStock: true,
        stockQuantity: 20,
        variants: [],
        specifications: { 'Capacity': '655L', 'Type': 'Side by Side', 'Compressor': 'Smart Inverter' },
        warranty: '1 Year LG Warranty + 10 Years Compressor',
        seller: 'LGIndia',
        isSponsored: false,
    },
    {
        name: 'Whirlpool 7.5 Kg Washing Machine',
        category: 'appliances',
        subCategory: 'washing',
        description: 'Fully automatic top load with 6th Sense technology.',
        images: ['https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=500'],
        price: 22990,
        originalPrice: 28990,
        discountPercentage: 21,
        rating: 4.3,
        reviewCount: 5678,
        inStock: true,
        stockQuantity: 50,
        variants: [],
        specifications: { 'Capacity': '7.5 Kg', 'Type': 'Top Load', 'Spin Speed': '740 RPM' },
        warranty: '2 Years Whirlpool Warranty',
        seller: 'WhirlpoolIndia',
        isSponsored: false,
    },
    {
        name: 'Voltas 1.5 Ton 5 Star Inverter Split AC',
        category: 'appliances',
        subCategory: 'ac',
        description: 'Voltas split AC with adjustable inverter compressor.',
        images: ['https://images.unsplash.com/photo-1631545806609-49c7b8ed3d88?w=500'],
        price: 38990,
        originalPrice: 52990,
        discountPercentage: 26,
        rating: 4.2,
        reviewCount: 4567,
        inStock: true,
        stockQuantity: 40,
        variants: [],
        specifications: { 'Capacity': '1.5 Ton', 'Star Rating': '5 Star', 'Compressor': 'Inverter' },
        warranty: '1 Year + 5 Years Compressor',
        seller: 'VoltasIndia',
        isSponsored: true,
    },
    {
        name: 'Prestige Iris 750W Mixer Grinder',
        category: 'appliances',
        subCategory: 'kitchen',
        description: 'Prestige Iris with 3 stainless steel jars.',
        images: ['https://images.unsplash.com/photo-1585515320310-259814833e62?w=500'],
        price: 3499,
        originalPrice: 5495,
        discountPercentage: 36,
        rating: 4.3,
        reviewCount: 12345,
        inStock: true,
        stockQuantity: 200,
        variants: [],
        specifications: { 'Power': '750W', 'Jars': '3', 'Speed': '3 Speed + Pulse' },
        warranty: '2 Years Prestige Warranty',
        seller: 'PrestigeIndia',
        isSponsored: false,
    },
    {
        name: 'Pigeon Healthifry Air Fryer 4.2L',
        category: 'appliances',
        subCategory: 'kitchen',
        description: 'Digital air fryer with touch control and 360° air circulation.',
        images: ['https://images.unsplash.com/photo-1626509653291-18d9a934b9db?w=500'],
        price: 3999,
        originalPrice: 6995,
        discountPercentage: 43,
        rating: 4.1,
        reviewCount: 8765,
        inStock: true,
        stockQuantity: 300,
        variants: [],
        specifications: { 'Capacity': '4.2L', 'Power': '1200W', 'Control': 'Digital Touch' },
        warranty: '1 Year Pigeon Warranty',
        seller: 'PigeonIndia',
        isSponsored: false,
    },
    {
        name: 'IKEA KALLAX Shelf Unit',
        category: 'home',
        subCategory: 'furniture',
        description: 'Versatile KALLAX shelf for storage and display.',
        images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=500'],
        price: 7999,
        originalPrice: 9999,
        discountPercentage: 20,
        rating: 4.4,
        reviewCount: 2345,
        inStock: true,
        stockQuantity: 40,
        variants: [{ name: 'Color', options: ['White', 'Black-Brown', 'Oak Effect'] }],
        specifications: { 'Dimensions': '147 x 77 x 39 cm', 'Material': 'Particleboard', 'Shelves': '8' },
        warranty: '10 Years IKEA Warranty',
        seller: 'IKEAIndia',
        isSponsored: false,
    },
    {
        name: 'Wakefit Orthopedic Memory Foam Mattress',
        category: 'home',
        subCategory: 'furniture',
        description: 'Wakefit mattress with 3-zone support and cooling gel.',
        images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500'],
        price: 12999,
        originalPrice: 19999,
        discountPercentage: 35,
        rating: 4.3,
        reviewCount: 34567,
        inStock: true,
        stockQuantity: 100,
        variants: [{ name: 'Size', options: ['Single', 'Double', 'Queen', 'King'] }],
        specifications: { 'Type': 'Memory Foam', 'Thickness': '8 inch', 'Firmness': 'Medium Firm' },
        warranty: '10 Years Wakefit Warranty',
        seller: 'WakefitIndia',
        isSponsored: true,
    },
    {
        name: 'Philips Ambilight 55 inch 4K Smart TV',
        category: 'electronics',
        subCategory: 'tv',
        description: 'Philips Ambilight TV with immersive 3-sided lighting.',
        images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500'],
        price: 69990,
        originalPrice: 89990,
        discountPercentage: 22,
        rating: 4.5,
        reviewCount: 1234,
        inStock: true,
        stockQuantity: 30,
        variants: [],
        specifications: { 'Display': '55 inch 4K UHD', 'HDR': 'Dolby Vision', 'Smart TV': 'Google TV' },
        warranty: '2 Years Philips Warranty',
        seller: 'PhilipsIndia',
        isSponsored: false,
    },
    {
        name: 'Sony Bravia 65 inch OLED TV',
        category: 'electronics',
        subCategory: 'tv',
        description: 'Sony Bravia XR OLED with Cognitive Processor XR.',
        images: ['https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=500'],
        price: 199990,
        originalPrice: 249990,
        discountPercentage: 20,
        rating: 4.8,
        reviewCount: 567,
        inStock: true,
        stockQuantity: 15,
        variants: [],
        specifications: { 'Display': '65 inch OLED', 'Processor': 'Cognitive XR', 'HDR': 'Dolby Vision/Atmos' },
        warranty: '2 Years Sony Warranty',
        seller: 'SonyIndia',
        isSponsored: false,
    },
    {
        name: 'Maybelline Fit Me Foundation',
        category: 'beauty',
        subCategory: 'makeup',
        description: 'Matte + Poreless foundation for normal to oily skin.',
        images: ['https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=500'],
        price: 499,
        originalPrice: 599,
        discountPercentage: 17,
        rating: 4.2,
        reviewCount: 45678,
        inStock: true,
        stockQuantity: 1000,
        variants: [{ name: 'Shade', options: ['120 Classic Ivory', '128 Warm Nude', '230 Natural Buff'] }],
        specifications: { 'Finish': 'Matte', 'Coverage': 'Medium', 'Type': 'Liquid' },
        warranty: '6 Months',
        seller: 'MaybellineIndia',
        isSponsored: false,
    },
    {
        name: 'MAC Ruby Woo Lipstick',
        category: 'beauty',
        subCategory: 'makeup',
        description: 'Iconic matte red lipstick with long-lasting formula.',
        images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=500'],
        price: 1950,
        originalPrice: 2100,
        discountPercentage: 7,
        rating: 4.6,
        reviewCount: 23456,
        inStock: true,
        stockQuantity: 500,
        variants: [],
        specifications: { 'Finish': 'Retro Matte', 'Shade': 'Ruby Woo', 'Undertone': 'Blue Red' },
        warranty: '12 Months',
        seller: 'MACCosmetics',
        isSponsored: true,
    },
    {
        name: 'The Ordinary Niacinamide 10% + Zinc 1%',
        category: 'beauty',
        subCategory: 'skincare',
        description: 'High-strength vitamin and mineral formula for blemishes.',
        images: ['https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=500'],
        price: 590,
        originalPrice: 750,
        discountPercentage: 21,
        rating: 4.5,
        reviewCount: 56789,
        inStock: true,
        stockQuantity: 800,
        variants: [],
        specifications: { 'Volume': '30ml', 'Key Ingredient': 'Niacinamide', 'Skin Type': 'All' },
        warranty: '24 Months',
        seller: 'TheOrdinary',
        isSponsored: false,
    },
    {
        name: 'Forest Essentials Soundarya Radiance Cream',
        category: 'beauty',
        subCategory: 'skincare',
        description: 'Luxurious anti-aging cream with 24K gold and natural oils.',
        images: ['https://images.unsplash.com/photo-1570194065650-d99fb4b38b17?w=500'],
        price: 5975,
        originalPrice: 6975,
        discountPercentage: 14,
        rating: 4.4,
        reviewCount: 3456,
        inStock: true,
        stockQuantity: 100,
        variants: [],
        specifications: { 'Volume': '50g', 'Key Ingredient': '24K Gold', 'Type': 'Night Cream' },
        warranty: '12 Months',
        seller: 'ForestEssentials',
        isSponsored: false,
    },
    {
        name: 'Dyson Airwrap Complete Long',
        category: 'beauty',
        subCategory: 'haircare',
        description: 'Dyson Airwrap for multiple hair styles with no heat damage.',
        images: ['https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=500'],
        price: 45900,
        originalPrice: 49900,
        discountPercentage: 8,
        rating: 4.7,
        reviewCount: 2345,
        inStock: true,
        stockQuantity: 50,
        variants: [],
        specifications: { 'Power': '1300W', 'Attachments': '6', 'Technology': 'Coanda Effect' },
        warranty: '2 Years Dyson Warranty',
        seller: 'DysonIndia',
        isSponsored: true,
    },
    {
        name: 'Philips BHH880 Hair Straightener Brush',
        category: 'beauty',
        subCategory: 'haircare',
        description: 'ThermoProtect heated styling brush for straight hair.',
        images: ['https://images.unsplash.com/photo-1522338140262-f46f5913618a?w=500'],
        price: 2495,
        originalPrice: 3495,
        discountPercentage: 29,
        rating: 4.2,
        reviewCount: 6789,
        inStock: true,
        stockQuantity: 200,
        variants: [],
        specifications: { 'Temperature': '170-200°C', 'Heat Up': '50 seconds', 'Bristles': 'Natural' },
        warranty: '2 Years Philips Warranty',
        seller: 'PhilipsIndia',
        isSponsored: false,
    },
    {
        name: 'Wildcraft Hiking Backpack 45L',
        category: 'fashion',
        subCategory: 'bags',
        description: 'Durable hiking backpack with rain cover.',
        images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=500'],
        price: 2999,
        originalPrice: 4999,
        discountPercentage: 40,
        rating: 4.3,
        reviewCount: 5678,
        inStock: true,
        stockQuantity: 150,
        variants: [{ name: 'Color', options: ['Black', 'Blue', 'Orange'] }],
        specifications: { 'Capacity': '45L', 'Material': 'Polyester', 'Rain Cover': 'Included' },
        warranty: '5 Years Wildcraft Warranty',
        seller: 'WildcraftIndia',
        isSponsored: false,
    },
    {
        name: 'American Tourister Polycarbonate Luggage',
        category: 'fashion',
        subCategory: 'bags',
        description: 'Hard-sided spinner luggage with TSA lock.',
        images: ['https://images.unsplash.com/photo-1565026057447-bc90a3dceb87?w=500'],
        price: 4999,
        originalPrice: 8999,
        discountPercentage: 44,
        rating: 4.4,
        reviewCount: 12345,
        inStock: true,
        stockQuantity: 100,
        variants: [{ name: 'Size', options: ['Small', 'Medium', 'Large'] }],
        specifications: { 'Material': 'Polycarbonate', 'Wheels': '4 Spinner', 'Lock': 'TSA Approved' },
        warranty: '5 Years International Warranty',
        seller: 'AmericanTourister',
        isSponsored: false,
    },
    {
        name: 'Ray-Ban Aviator Classic Sunglasses',
        category: 'fashion',
        subCategory: 'accessories',
        description: 'Iconic Ray-Ban Aviator with polarized lenses.',
        images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500'],
        price: 8490,
        originalPrice: 10490,
        discountPercentage: 19,
        rating: 4.6,
        reviewCount: 7890,
        inStock: true,
        stockQuantity: 80,
        variants: [{ name: 'Lens', options: ['Green', 'Brown', 'Blue'] }],
        specifications: { 'Frame': 'Metal', 'Lens': 'Crystal Polarized', 'UV Protection': '100%' },
        warranty: '2 Years Ray-Ban Warranty',
        seller: 'RayBanIndia',
        isSponsored: false,
    },
    {
        name: 'Titan Automatic Mechanical Watch',
        category: 'fashion',
        subCategory: 'accessories',
        description: 'Titan automatic watch with exhibition back.',
        images: ['https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=500'],
        price: 12995,
        originalPrice: 17995,
        discountPercentage: 28,
        rating: 4.4,
        reviewCount: 3456,
        inStock: true,
        stockQuantity: 50,
        variants: [],
        specifications: { 'Movement': 'Automatic', 'Case': 'Stainless Steel', 'Water Resistance': '50m' },
        warranty: '2 Years Titan Warranty',
        seller: 'TitanIndia',
        isSponsored: false,
    },
];

const seedDB = async () => {
    try {
        await mongoose.connect(MONGODB_URI);
        console.log('✅ Connected to MongoDB');

        // Clear existing data
        await Product.deleteMany({});
        console.log('🗑️  Cleared existing products');

        // Insert new data
        await Product.insertMany(products);
        console.log(`🌱 Seeded ${products.length} products`);

        process.exit(0);
    } catch (error) {
        console.error('❌ Seeding failed:', error);
        process.exit(1);
    }
};

seedDB();
